const NS_INTERVIEW = 'interview';

const SET_VISIBLE_ID_INTERVIEWER = `${NS_INTERVIEW}/setVisibleIdInterview`;
const SET_VISIBLE_INTERVIEWER_ID = `${NS_INTERVIEW}/setVisibleInterviewId`;
const SET_VISIBLE_DATE_INTERVIEWER = `${NS_INTERVIEW}/setVisibleDateInterview`;

const SET_VISIBLE_NAME_INTERVIEWER = `${NS_INTERVIEW}/setVisibleNameInterview`;

export {
  SET_VISIBLE_ID_INTERVIEWER,
  SET_VISIBLE_INTERVIEWER_ID,
  SET_VISIBLE_DATE_INTERVIEWER,
  SET_VISIBLE_NAME_INTERVIEWER,
};
