@startuml regsiterSequence
!theme reddress-lightblue

autonumber 1.1
actor User
control  jobController
boundary jobService
database Mongodb

User -> jobController: getAllJob()
jobController -> jobController: validate

@enduml
