@startuml addJob
!theme reddress-lightblue

autonumber 1.1
actor User
control  jobRouter
control  jobController
boundary jobService
database Mongodb

User -> jobController: createJobHandler(req, res)
activate jobController
jobController -> jobController: validate
jobController -> jobService: createJob(jobData)
activate jobService
jobService -> Mongodb: getJob(jobData)
activate Mongodb
Mongodb --> jobService: success
deactivate Mongodb
jobService --> jobController: jobData
deactivate jobService
jobController --> User: jobData
deactivate jobController

@enduml
