@startuml addJob
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  jobController
boundary jobService
database Mongodb

User -> UI: add job
activate UI
UI -> jobController: call api
activate jobController

alt#Gold #LightBlue Successful case
    jobController -> jobController: checkAuth()
else #Pink Failure
    jobController --> UI: auth error
    UI --> User: display error
end

jobController -> jobService: createJob()

alt#Gold #LightBlue Successful case
    activate jobService
    jobService -> Mongodb: query()
    activate Mongodb
    Mongodb -> Mongodb: Validate
    Mongodb --> jobService: success
    jobService --> jobController: jobData
    jobController --> UI: data
    UI --> User: display data
else #Pink Failure
    Mongodb --> jobService: mongoose exception
    deactivate Mongodb
    jobService --> jobController: redirect exception
    deactivate jobService
    jobController --> UI: error message
    deactivate jobController
    UI --> User: show error
    deactivate UI
end

@enduml
