@startuml getAllUser
!theme reddress-lightblue

autonumber 1.1
actor User
control  userController
boundary userService
database Mongodb

User -> userController: getAllUsersHandler(req, res)
activate userController
userController -> userController: validate
userController -> userService: getUsers(filter, options)
activate userService
userService -> Mongodb: find()
activate Mongodb
Mongodb --> userService: success
deactivate Mongodb
userService --> userController: userData
deactivate userService
userController --> User: userData
deactivate userController

@enduml
