@startuml getAllUser
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  userController
boundary userService
database Mongodb

User -> UI: get all User
activate UI
UI -> userController: call api
deactivate UI
activate userController
userController -> userController: checkAuth()
userController -> userService: getUsers()
activate userService
userService -> Mongodb: find()
activate Mongodb
Mongodb -> Mongodb: Validate
Mongodb --> userService: success
deactivate Mongodb
userService --> userController: userData
deactivate userService
userController --> UI: userData
deactivate userController
activate UI
UI --> User: display data
deactivate UI

@enduml
