@startuml authClass
!theme reddress-lightblue

skinparam classAttributeIconSize 0
class auth.controller{
  - {field} authService: object
  - {field} tokenService: object
  - {field} userService: object

  + {method} registerHandler(req: express.Request, res: express.Response): void
  + {method} loginHandler(req: express.Request, res: express.Response): void
  + {method} logoutHandler(req: express.Request, res: express.Response): void
  + {method} forgotPassHandler(req: express.Request, res: express.Response): void
  + {method} refreshTokenHandler(req: express.Request, res: express.Response): void
}

class auth.service{
  - {field} userService: object
  - {field} tokenService: object
  - {field} eventProducer: event

  + {method} loginByUsernamePassword(username: string, password:string): void
  + {method} forgotPass(username: string, email: string): void
  + {method} logout(refreshToken: string): void
  + {method} refreshAuth(refreshToken: string): void
}

class auth.router{
  + {field} router: express.Router
}

class user.service{
  - {field} User: mongoose.Schema

  + {method} createUser(userBody: object): void
  + {method} getUserByUsername(username: string): void
  + {method} getUserByUsernameAndEmail(username: string, email:string): void
  + {method} getUsers(filter: object, options: object): void
  + {method} getUserById(id: string): void
  + {method} updateUserById(userId: string, updateBody: object): void
  + {method} deleteUserById(userId: string): void
  + {method} updateUserAvartarById(userId: string, avatar: string): void
  + {method} getUserAvartarById(userId: string): void
  + {method} getUserIdFromHeaderToken(authorization: string): void
}

class token.service{
  - {field} Token: mongoose.Schema

  + {method} generateToken(userId: string, expires: Moment, type: string, secret: string): void
  + {method} saveToken(token: string, userId: string, expires: Moment, type: string, blacklisted: boolean): void
  + {method} verifyToken(token: string, type: string): void
  + {method} deleteByRefreshToken(refreshToken: string): void
  + {method} generateAuthTokens(user: object): void
}

class schema.Token {
  + {field} token: String
  + {field} userId: ObjectId
  + {field} type: enum 
  + {field} expires: Date
  + {field} blackedlisted: Boolean
}

class schema.User {
  + {field} username: String
  + {field} password: String
  + {field} email: String 
  + {field} sex: enum
  + {field} firstName: String 
  + {field} midName: String
  + {field} lastName: String 
  + {field} fullName: String 
  + {field} unsignedFullName: String
  + {field} phone: String
  + {field} address: String
  + {field} dateOfBirth: Date
  + {field} languages: String
  + {field} maritalStatus: String
  + {field} role: enum
  + {field} jobStatus: Object
  + {field} createdAt: Date
  + {field} updatedAt: Date

  + {method} isUsernameTaken: Boolean
  + {method} isEmailTaken: Boolean
  + {method} isPasswordMatch: Boolean
  + {method} isPasswordMatch: Boolean
}

auth.controller ..> auth.service
auth.router ..>	 auth.controller
auth.service ..> user.service
auth.service ..> token.service
user.service ..> schema.User
token.service ..> schema.Token
@enduml
