@startuml authClass
!theme reddress-lightblue

skinparam classAttributeIconSize 0
class job.controller{
    - {field} jobService: object

    + {method} addJobPosting(req: express.Request, res: express.Response): void
    + {method} getAllJob(req: express.Request, res: express.Response): void
    + {method} getJob(req: express.Request, res: express.Response): void
    + {method} editJob(req: express.Request, res: express.Response): void
    + {method} changeJobStatus(req: express.Request, res: express.Response): void
    + {method} deleteJob(req: express.Request, res: express.Response): void
}

class job.service{
    + {method} createJob(jobData: Object): void
    + {method} getAllJob(filter: Object, options: Object): void
    + {method} getAllPublishedJob(filter: Object, options: Object): void
    + {method} getJobById(id: string): void
    + {method} editJobById(id: string, jobData: Object): void
    + {method} deleteJobById(id: string): void
}

class job.router{
    + {field} router: express.Router
}

class user.service{
  + {method} createUser(userBody: object): void
  + {method} getUserByUsername(username: string): void
  + {method} getUsers(filter: object, options: object): void
  + {method} getUserById(id: string): void
  + {method} updateUserById(userId: string, updateBody: object): void
  + {method} deleteUserById(userId: string): void
}


class schema.Job {

}

class schema.User {

}

job.router ..> job.controller
job.controller ..> job.service
job.controller ..> user.service
job.service ..> schema.Job
user.service ..> schema.User
@enduml