@startuml authClass
!theme reddress-lightblue

skinparam classAttributeIconSize 0
class job.controller{
    - {field} jobService: object

    + {method} addJobPosting(req: express.Request, res: express.Response): void
    + {method} getAllJob(req: express.Request, res: express.Response): void
    + {method} getJob(req: express.Request, res: express.Response): void
    + {method} editJob(req: express.Request, res: express.Response): void
    + {method} changeJobStatus(req: express.Request, res: express.Response): void
    + {method} deleteJob(req: express.Request, res: express.Response): void
}

class job.service{
    + {method} createJob(jobData: Object): void
    + {method} getAllJob(filter: Object, options: Object): void
    + {method} getAllPublishedJob(filter: Object, options: Object): void
    + {method} getJobById(id: string): void
    + {method} editJobById(id: string, jobData: Object): void
    + {method} deleteJobById(id: string): void
}

class job.router{
    + {field} router: express.Router
}

class user.service{
  + {method} createUser(userBody: object): void
  + {method} getUserByUsername(username: string): void
  + {method} getUsers(filter: object, options: object): void
  + {method} getUserById(id: string): void
  + {method} updateUserById(userId: string, updateBody: object): void
  + {method} deleteUserById(userId: string): void
}


class schema.Job {
    + {field} userId: ObjectId
    + {field} candidateId: [ObjectId]
    + {field} title: String
    + {field} unsignedTitle: String
    + {field} status:  enum 
    + {field} department: enum
    + {field} jobType:  String 
    + {field} location: String 
    + {field} jobDescription:  String
    + {field} jobDescription: String
    + {field} shortDes: String
    + {field} skill: String
    + {field} experience: String
    + {field} minSalary: Number
    + {field} maxSalary: Number
    + {field} currency: String
    + {field} createdAt: Date
    + {field} updatedAt: Date
}

class schema.User {
  + {field} username: String
  + {field} password: String
  + {field} email: String 
  + {field} sex: enum
  + {field} firstName: String 
  + {field} midName: String
  + {field} lastName: String 
  + {field} fullName: String 
  + {field} unsignedFullName: String
  + {field} phone: String
  + {field} address: String
  + {field} dateOfBirth: Date
  + {field} languages: String
  + {field} maritalStatus: String
  + {field} role: enum
  + {field} jobStatus: Object
  + {field} createdAt: Date
  + {field} updatedAt: Date

  + {method} isUsernameTaken: Boolean
  + {method} isEmailTaken: Boolean
  + {method} isPasswordMatch: Boolean
  + {method} isPasswordMatch: Boolean
}

job.router ..> job.controller
job.controller ..> job.service
job.controller ..> user.service
job.service ..> schema.Job
user.service ..> schema.User
@enduml