@startuml authClass
!theme reddress-lightblue

skinparam classAttributeIconSize 0
class user.controller{
    - {field} userService: object

    + {method} createUserHandler(req: express.Request, res: express.Response): void
    + {method} getAllUsersHandler(req: express.Request, res: express.Response): void
    + {method} getUserHandler(req: express.Request, res: express.Response): void
    + {method} updateUserHandler(req: express.Request, res: express.Response): void
    + {method} updateUserAvatarHandler(req: express.Request, res: express.Response): void
    + {method} deleteUserHandler(req: express.Request, res: express.Response): void
}

class user.service{
    + {method} createUser(userBody: Object): void
    + {method} getUserByUsername(username: string): void
    + {method} getUserByUsernameAndEmail(username: string, email: string): void
    + {method} getUserIdFromHeaderToken(authorization: string): void
    + {method} getUsers(filter: Object, options: Object): void
    + {method} getUserById(id: string): void
    + {method} updateUserById(userId: string, updateBody: Object): void
    + {method} updateUserAvatarById(userId: string, avatar: Object): void
    + {method} deleteUserById(userId: string): void
}

class user.router{
    + {field} router: express.Router
}

class schema.User {
  + {field} username: String
  + {field} password: String
  + {field} email: String 
  + {field} sex: enum
  + {field} firstName: String 
  + {field} midName: String
  + {field} lastName: String 
  + {field} fullName: String 
  + {field} unsignedFullName: String
  + {field} phone: String
  + {field} address: String
  + {field} dateOfBirth: Date
  + {field} languages: String
  + {field} maritalStatus: String
  + {field} role: enum
  + {field} jobStatus: Object
  + {field} createdAt: Date
  + {field} updatedAt: Date

  + {method} isUsernameTaken: Boolean
  + {method} isEmailTaken: Boolean
  + {method} isPasswordMatch: Boolean
  + {method} isPasswordMatch: Boolean
}

user.router ..> user.controller
user.controller ..> user.service
user.service ..> schema.User
@enduml