@startuml forgotPassSequence
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  authController
boundary authService
boundary mailService
database Mongodb

User -> UI: forgotPass
activate UI
UI -> authController: forgotPassHandler()
activate authController

authController ->> authService: logout()
activate authService
alt#Gold #LightBlue Successful case
    authService -> Mongodb: forgotPass()
    activate Mongodb
    Mongodb -> Mongodb: validate
    Mongodb --> authService: data
    authService --> authController: ok
    authController --> UI: success message
    UI --> User: show data
    authService -->> mailService: sendMail
    activate mailService
    mailService --> User: newPass
    deactivate mailService
else #Pink Failure
    Mongodb --> authService: exception
    deactivate Mongodb
    authService --> authController: redirect exception
    deactivate authService
    authController --> UI: error message
    deactivate authController
    UI --> User: show error
    deactivate UI
deactivate UI
end

@enduml