@startuml regsiterSequence
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  authController
boundary userService
boundary tokenService
database Mongodb

User -> UI: Register
activate UI
UI -> authController: registerHandler()
deactivate UI
activate authController
authController -> authController: validate
authController ->> userService: createUser()
activate userService
userService -> userService: validateEmail/User()
userService -> Mongodb: getUser()
activate Mongodb
Mongodb --> userService: success
deactivate Mongodb
userService --> authController: userData
deactivate userService
deactivate authController

authController ->> tokenService: generateAuthToken()
activate authController
activate tokenService
tokenService -> tokenService: validateToken()
tokenService -> Mongodb: getToken()
activate Mongodb
Mongodb --> tokenService: success
deactivate Mongodb
tokenService --> authController: tokenData
deactivate tokenService
authController --> UI
deactivate authController
activate UI
UI --> User
deactivate UI
@enduml
