@startuml add Interview 
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  interviewController
boundary interviewService
database Mongodb


User -> UI: add interview
activate UI
UI -> interviewController: call api
deactivate UI
activate interviewController
interviewController -> interviewController: checkAuth()
interviewController -> interviewService: createInterview()
activate interviewService
interviewService -> Mongodb: save()
activate Mongodb
Mongodb -> Mongodb: Validate
Mongodb --> interviewService: success
deactivate Mongodb
interviewService --> interviewController: interviewData
deactivate interviewService
interviewController --> UI: interviewData
deactivate interviewController
activate UI
UI --> User: display data
deactivate UI

@enduml
