@startuml delete Interview
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  interviewController
boundary interviewService
database Mongodb


User -> UI: delete interview
activate UI
UI -> interviewController: call api
deactivate UI
activate interviewController
interviewController -> interviewController: checkAuth()
interviewController -> interviewService: deleteInterviewById()
activate interviewService
interviewService -> Mongodb: findByIdAndDelete()
activate Mongodb
Mongodb -> Mongodb: Validate
Mongodb --> interviewService: success
deactivate Mongodb
interviewService --> interviewController: interviewData
deactivate interviewService
interviewController --> UI: interviewData
deactivate interviewController
activate UI
UI --> User: display data
deactivate UI

@enduml
