@startuml addCandidate
!theme reddress-lightblue

autonumber 1.1
actor User
participant UI
control  candidateController
boundary candidateService
database Mongodb


User -> UI: add candidate
activate UI
UI -> candidateController: call api
activate candidateController
alt#Gold #LightBlue Successful case
    candidateController -> candidateController: checkAuth()
else #Pink Failure
    candidateController --> UI: auth error
    UI --> User: display error
end
candidateController -> candidateService: createCandidate()
activate candidateService
candidateService -> Mongodb: save()

alt#Gold #LightBlue Successful case
    activate Mongodb
    Mongodb -> Mongodb: validate
    Mongodb --> candidateService: success
    candidateService --> candidateController: candidateData
    candidateController --> UI: candidateData
    UI --> User: display data
else #Pink Failure
    Mongodb --> candidateService: mongoose exception
    deactivate candidateService
    deactivate Mongodb
    candidateService --> candidateController: redirect exception
    candidateController --> UI: error message
    deactivate candidateController
    UI --> User: show error
    deactivate Mongodb
    deactivate UI
end

@enduml
