name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build-ui:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master
      id: buildx

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./
        file: ./fe/Dockerfile
        # platforms: linux/amd64,linux/arm64,linux/arm/v7
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rms-ui

    - name: SSH deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_KEY }}
        command_timeout: 200m
        port: 22
        script: |
          ./deploy.sh
